<?php

namespace WS\apiBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function countByNameLastName($name,$lastname)
    {
        $qb = $this
            ->createQueryBuilder('u')
            ->select('COUNT(u)')
            ->where('u.name LIKE :name')
            ->andWhere('u.lastName LIKE :lname')
            ->setParameter('name','%'.$name.'%')
            ->setParameter('lname','%'.$lastname.'%')
        ;

        $result = $qb->getQuery()->getSingleScalarResult();

        return $result;
    }
}
