<?php

namespace WS\appBundle\Repository;

/**
 * MyAppRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MyAppRepository extends \Doctrine\ORM\EntityRepository
{
}
